### PR TITLE
Change snoozing UI for better clarity

### PR DESCRIPTION
**Pull request by akkaneror**
I changed the UI to a cleaner and more simplistic look with bigger menu and even bigger font than before.  Ah, I also add a "Cancel" option for those who might have second thought on snoozing it, or maybe they just simply misclick the notification button. Basically "Cancel" will not block that incoming sounds. 
@rachelgk seem to like it. 

Plus, I change "this sound will block for x mins" to "\<Specific type of sound\> will block for x mins"

device-2020-08-11-202906

### CODE REVIEW

**Comment by higherdefender** [comment]
Good idea!

1. Can you remove the confidence level? Because essentially the speech is snoozed not Speech of 100% confidence
2. Use “Snooze” instead of “Block“
3. Make the sound (speech in this case) bold. 
4. What happens if the sound doesn’t fit in a line? Say “Utensils and Cutlery”? How would the UI look then? 
5. Can I see the cancel button as well?

**Comment by akkaneror** [comment]
1. Yes!
2. Yes!
3. Gotcha
4. It will wrap itself and centered (picture below)
5. Of course.
device-2020-08-11-221316

**Comment by higherdefender** [comment]
This looks great. Assuming you’ll of course remove “and many more..”, go ahead and merge it to main.

**Comment by akkaneror** [comment]
Yeah that was just a text demo to showcase since I don't have access to Utensil and Cutlery right now haha :)

**Comment by jonfroehlich** [comment]
Can you update the text to say "Snooze <label name> for:" rather than "Snooze time for <label name>:"

**Comment by rachelgk** [comment]
I like the bigger typography on the 1 min, 2 min, etc.  (much more readable
than before), but I’m thinking that it should not be larger than the header
for hierarchy purposes.  (Header is more important and first read) I think
the minutes should be reduced slightly in size to match the header, or be a
tiny bit smaller.  (But still large enough to read clearly). It’s
definitely improved by not having the grey background menu from before.

**Comment by akkaneror** [comment]
I make the Title a bit larger, at the same time make the font for "Selecting" a bit smaller, but I thought it might harder to read, so to compensate, I make the Selection in Bold. 

What do you think? 
 
device-2020-08-12-124729

**Comment by rachelgk** [comment]
Is the header Snooze for Speech the same font as the min selection?  I
think they look different and that is bothering me because they are too
similar without being the same.  If we want to use two different fonts they
should have more of a style difference.  I also think the minutes still
look larger than the header.   But it is looking better overall, I think
the bolded mins is fine.  What do you all think?

**Comment by higherdefender** [comment]
I agree that this much looks better! 

Rachel’s concern is also valid: we should have similar font styles across the app as much as much as possible, and if they have to be different, make them really different to be visible. Otherwise, it looks like we made a styling mistake. 

Perhaps we can have a meta file that lists all font styles within headers? (See android styling that Jon shared). And then you can apply these h1s and h2s consistently throughout the app.

**Comment by akkaneror** [comment]
From @rachelgk and @higherdefender suggestion, I have made four options, which one do you prefer the most?

Normal-Condensed Font, Normal Text Selection

device-2020-08-12-195158

Normal-Condensed Font, **Bold** Text  Selection

bold

Normal-Regular Font, Normal Text Selection.

device-2020-08-12-201450

**Bold**-Regular Font, Bold Text Selection.

aa

**Comment by higherdefender** [comment]
I like the first two; any of those are fine as long as we’re consistent
throughout the app (that is, for other screens as well such as welcome).

Also, maybe try with sound (speech) having the same color as the selection
(white)?
-- 
dhruvjain.info | twitter.com/dj_hci

**Comment by rachelgk** [comment]
I like the first two as well and I like DJ's idea to see what speech looks
like white to emphasize it.

**Pull request merged**
