### PR TITLE
Add animation for better readability/UX and update deprecated function

### LINKED ISSUE #3: UX Improvements
### 1. The first improvement is changing the way "recording" button behave on Wearable app. 
I changed the label to "LISTENING" as we press the "mic" icon, to indicate the user that we are recording their surrounding.
I also add a subtle Pulsing animation to further emphasize on that fact alone, because it's important for the users to be aware that they are being listened.

### LINKED ISSUE #5: UI Scalability
I borrowed another WearOS watch to test on different UI if our app hold ups, and it turned out our UI is not very scalable with smaller watch size (I test it with our master-branch UI)
- the button is mis-located.
- text collapse on each other.

I'm working on making it scalable with (possibly) all type of watch sizes.
@higherdefender What do you think?

### PR DESCRIPTION
**Pull request by akkaneror**

### CODE REVIEW

**Review by higherdefender — COMMENTED** [review]
@akkaneror Could you add before/after images or gifs for us to see what was changed? Thanks.

**Comment by akkaneror** [comment]
@higherdefender 
BEFORE
before


AFTER
after

**Comment by higherdefender** [comment]
Thanks for this! Neat idea, but the animation shape (circle) should reflect the shape of the button (oval). So, maybe make the button a round shape as well?

Also, this should have been fixed before but the text should show "Welcome **to** SoundWatch". And "Listening.." should not be in caps for UI consistency (since the preceding text is not..) Can you make those changes?

**Comment by akkaneror** [comment]
> Thanks for this! Neat idea, but the animation shape (circle) should reflect the shape of the button (oval). So, maybe make the button a round shape as well?
> 
> Also, this should have been fixed before but the text should show "Welcome **to** SoundWatch". And "Listening.." should not be in caps for UI consistency (since the preceding text is not..) Can you make those changes?

I agree with the text not in CAPS, but I did try the _oval shape_ of the animation before and it doesn't look quite fit as I expected, especially this is replicating the idea of a **pulsing radar**.
Furthermore, I think since the shape of the watch is rounded so the pulsing animation fit the **watch shape** instead of the **button shape**. 
Another possible change, like you mentioned, is that we could change the button shape to rounded instead.
How do you think? Which one do prefer :)

**Comment by higherdefender** [comment]
Yeah, I prefer the round button shape too for the reasons you outlined (watch is round).

**Comment by akkaneror** [comment]
I updated the button shape, turned out there isn't a default option to have a circular ImageView, so I need to make a workaround to turn it circle, that might be why Hung chose to make it oval :)

after

**Comment by higherdefender** [comment]
This is nice! Well done.

For consistency, can you make sure the pulse animation isn’t cut off by the
text box at the bottom? It’s not at the top textbox so should be
consistent. I think Rachel can give you good feedback on these things so
let’s add her soon.

Also, there are remaining fixes from our above discussion: (1) listening
should not be in caps, and (2) add “to”: “Welcome to SoundWatch”. Let’s fix
those things in this merge as well.


Update: @akkaneror Making sure you saw this.

**Comment by higherdefender** [comment]
Beautiful! Nice job @akkaneror!

**Comment by higherdefender** [comment]
Merged into main.

**Pull request merged**
